import React, { useState } from 'react';
import { HelpCircle } from 'lucide-react';

interface TooltipProps {
  term: string;
  definition?: string;
  children?: React.ReactNode;
  size?: number;
}

const definitions: Record<string, string> = {
  'WACC': 'Weighted Average Cost of Capital - The average rate a company pays to finance its assets. It represents the minimum return a company must earn to satisfy its investors.',
  'Terminal Value': 'The estimated value of a business beyond the explicit forecast period. It often represents 60-80% of total DCF value.',
  'DCF': 'Discounted Cash Flow - A valuation method that estimates the value of an investment based on its expected future cash flows, discounted to present value.',
  'EBITDA': 'Earnings Before Interest, Taxes, Depreciation & Amortization - A measure of operating profitability that excludes non-operating expenses.',
  'EV': 'Enterprise Value - The total value of a company including equity and debt, minus cash. It represents what it would cost to acquire the entire business.',
  'FCF': 'Free Cash Flow - Cash generated by operations minus capital expenditures. This is the cash available to pay investors.',
  'P/E Ratio': 'Price-to-Earnings Ratio - Stock price divided by earnings per share. Shows how much investors pay for each dollar of earnings.',
  'EV/EBITDA': 'Enterprise Value to EBITDA ratio - A valuation multiple that compares a company\'s total value to its operating earnings.',
  'Beta': 'A measure of a stock\'s volatility relative to the market. Beta > 1 means more volatile, Beta < 1 means less volatile.',
  'Risk-Free Rate': 'The theoretical return on an investment with zero risk, typically based on government bond yields.',
  'Equity Risk Premium': 'The excess return that investing in the stock market provides over a risk-free rate, compensating for higher risk.',
  'Terminal Growth': 'The perpetual growth rate used to calculate terminal value. Usually set to long-term GDP growth (2-3%).',
  'Discount Rate': 'The rate used to convert future cash flows to present value. Higher rates mean future cash flows are worth less today.',
  'NPV': 'Net Present Value - The sum of all future cash flows discounted to today\'s value.',
  'Shares Outstanding': 'Total number of shares currently held by all shareholders, used to calculate per-share metrics.',
  'Market Cap': 'Market Capitalization - Total market value of a company\'s outstanding shares (Share Price × Shares Outstanding).',
  'Gross Margin': 'Revenue minus Cost of Goods Sold, divided by Revenue. Shows profitability before operating expenses.',
  'Operating Margin': 'Operating income divided by revenue. Shows profitability from core business operations.',
  'Net Margin': 'Net income divided by revenue. Shows overall profitability after all expenses.',
  'ROE': 'Return on Equity - Net income divided by shareholder equity. Measures how efficiently a company uses equity to generate profits.',
  'ROA': 'Return on Assets - Net income divided by total assets. Measures how efficiently a company uses assets to generate profits.',
  'Current Ratio': 'Current assets divided by current liabilities. Measures ability to pay short-term obligations. Above 1.5 is healthy.',
  'Debt/Equity': 'Total debt divided by total equity. Measures financial leverage. Lower is generally safer.',
  'Interest Coverage': 'EBIT divided by interest expense. Shows ability to pay interest on debt. Above 3 is healthy.',
  'CapEx': 'Capital Expenditures - Money spent on acquiring or maintaining fixed assets like buildings and equipment.',
  'Working Capital': 'Current assets minus current liabilities. The capital used in day-to-day trading operations.',
  'Perpetuity': 'A constant stream of cash flows that continues forever, used in terminal value calculation.',
  'Intrinsic Value': 'The actual value of a company based on fundamental analysis, as opposed to its current market price.',
  'Upside': 'The potential percentage gain if the stock moves from current price to fair value.',
  'Comparable Companies': 'Similar public companies used as benchmarks for relative valuation multiples.',
  'Bull Case': 'Optimistic scenario assuming strong growth, margin expansion, and favorable market conditions.',
  'Bear Case': 'Pessimistic scenario assuming weak growth, margin compression, and challenging market conditions.',
  'Base Case': 'Most likely scenario based on current trends and reasonable assumptions.',
  'Revenue': 'The total amount of income generated by the sale of goods or services related to the company\'s primary operations.',
  'Net Income': 'The total profit of the company after all expenses, including taxes and interest, have been deducted.',
  'Total Debt': 'The sum of all short-term and long-term debt obligations.',
};

export const Tooltip: React.FC<TooltipProps> = ({ term, definition, children, size = 14 }) => {
  const [isVisible, setIsVisible] = useState(false);
  
  const displayText = definition || definitions[term] || `Definition for "${term}" not available.`;
  
  return (
    <span className="relative inline-flex items-center">
      {children}
      <button
        className="ml-1 text-gray-400 hover:text-red-400 transition-colors focus:outline-none"
        onMouseEnter={() => setIsVisible(true)}
        onMouseLeave={() => setIsVisible(false)}
        onClick={() => setIsVisible(!isVisible)}
        aria-label={`What is ${term}?`}
      >
        <HelpCircle size={size} />
      </button>
      
      {isVisible && (
        <div className="absolute z-50 bottom-full left-1/2 transform -translate-x-1/2 mb-2 w-72 p-3 bg-zinc-900 border border-red-500/30 rounded-lg shadow-xl text-sm text-gray-300">
          <div className="font-semibold text-red-400 mb-1">{term}</div>
          <div className="leading-relaxed">{displayText}</div>
          <div className="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2 rotate-45 w-2 h-2 bg-zinc-900 border-r border-b border-red-500/30"></div>
        </div>
      )}
    </span>
  );
};

export default Tooltip;
